### ISSUE TITLE
ログインしているかの確認を`page.tsx`でする

### ISSUE THREAD

**Issue by Yumax-panda** [Yumax-panda/full-stack#155]
`layout.tsx`をミドルウェアとしてつかうことはできない

ref: https://zenn.dev/meijin/articles/nextjs14-layout-as-middleware

**Comment by Yumax-panda** [comment]
一部のページでログインの確認を`layout.tsx`で行なっているが、それではログイン必要なページの秘匿が完全ではない

https://github.com/Yumax-panda/full-stack/blob/70f787a6194913672b4865b9120192b137038fc1/src/app/(withAuth)/layout.tsx#L11

## 要修正

- `layout.tsx`でログイン確認をしている場合、それを代わりに対応する`page.tsx`で行う
- (必要に応じて`layout.tsx`を削除する)

## 参考
- [Next.jsのルーティング方法](https://nextjs.org/docs/app/building-your-application/routing)
- [`layout.tsx`について](https://nextjs.org/docs/app/api-reference/file-conventions/layout)
- [ログインしているか確認するときに使う`getServerSession`](https://next-auth.js.org/configuration/nextjs#getserversession)

**Comment by bfs84** [comment]
**User Story**
Who: 外部ユーザー
What: 任意のユーザーのセッション情報を不正に取得できないようにする
Why: 現在の実装ではlayout.tsxでセッション確認しており、curlコマンドで攻撃者にセッション情報を盗まれるおそれがあるため
Where: full-stack

**受け入れ条件**
page.tsxでセッション確認を実施し結果のみlayout.tsxに渡すことで、クライアント側に秘匿情報が漏れない構造になっていること

**Comment by bfs84** [comment]
@Yumax-panda さん
お疲れ様です！
リモートリポジトリのブランチを切って作業をしようとしたところ、アクセス権がないようで
> fatal: unable to access 'https://github.com/Yumax-panda/full-stack.git/': The requested URL returned error: 403
と出たのでアクセス権の付与をお願いしてもよろしいでしょうか？
